### ISSUE TITLE
How to Cancel?

### ISSUE THREAD

**Issue by HackShitUp** [LeonardoCardoso/SwiftLinkPreview#108]
Not an issue, but I'm trying to figure out how to cancel requests (used when loading data in cells and canceling them in the cell's life cycle).

**Comment by wolfej94** [comment]
@HackShitUp did you get anywhere with this?

**Comment by LeonardoCardoso** [comment]
A preview is cancellable, like the example below:

```
let preview = slp.preview("Text containing URL",
                          onSuccess: { result in print("\(result)") },
                          onError: { error in print("\(error)")})
// preview.cancel() to cancel it.
```

**Comment by HackShitUp** [comment]
> @HackShitUp did you get anywhere with this?

I've moved on to using LPLinkPreview. Significantly better.

**Comment by HackShitUp** [comment]
@wolfej94 I've moved on to using LPLinkPreview. Significantly better.

**Comment by dhanrajdc7** [comment]
@HackShitUp Can you please share the code about LPLinkPreview to compare?
