### ISSUE TITLE
Can't add with SPM

### ISSUE THREAD

**Issue by cmcgheit** [LeonardoCardoso/SwiftLinkPreview#110]
I'm having an issue trying to add via swift package manager:

<img width="603" alt="Screen Shot 2020-02-25 at 11 04 51 AM" src="https://user-images.githubusercontent.com/24944725/75279383-204e3880-57d1-11ea-8b70-9dbb06d1523d.png">

I've tried adding the exact 3.1.0 version and up to the next major version via xcode and both are not working and give this error. I'm using xcode 11.3.

**Comment by LeonardoCardoso** [comment]
New version with the fix coming right up.
