### ISSUE TITLE
Bad URL timestamp (images)

### ISSUE THREAD

**Issue by n1k3c** [LeonardoCardoso/SwiftLinkPreview#114]
I have problems with parsing instagram/facebook images. 

Example url: [Instagram example](https://www.instagram.com/p/B-XzQGNAC3t/?igshid=vmz2wv97nteu)
Parsed image source with timestamp error: [Instagram Bad URL timestamp](https://instagram.fzag4-1.fna.fbcdn.net/v/t51.2885-15/e)

Should be something like this: [Expected result](https://instagram.fzag4-1.fna.fbcdn.net/v/t51.2885-15/e15/s640x640/91791468_201351684618595_7665007049890597802_n.jpg?_nc_ht=instagram.fzag4-1.fna.fbcdn.net&_nc_cat=107&_nc_ohc=uzrChEz8xy8AX9J0e4z&oh=a3b2a1dd77d93dff8bb9b37452154b3b&oe=5EACC8FE)

**Comment by LeonardoCardoso** [comment]
Fixed with the new version
![Simulator Screen Shot - iPhone 11 Pro - 2021-02-01 at 12 22 27](https://user-images.githubusercontent.com/1775157/106452473-3ad06d80-6488-11eb-873d-4b0af7f113fb.png)
