### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by gopalanrc** [LeonardoCardoso/SwiftLinkPreview#115]
I'm using Android variant of the library. Following link doesn't work
https://www.masterclass.com

I tried setting up the user agent by System.getProperty("http.agent"). But, no luck.

Any help is appreciated.

**Comment by LeonardoCardoso** [comment]
Fixed with the new version.
![Simulator Screen Shot - iPhone 11 Pro - 2021-02-01 at 12 23 55](https://user-images.githubusercontent.com/1775157/106452574-62bfd100-6488-11eb-894f-94dd2bc7abbc.png)
