### ISSUE TITLE
SwiftlinkPreview generating old preview

### ISSUE THREAD

**Issue by Razanajam** [LeonardoCardoso/SwiftLinkPreview#116]
Hi, it's a great library, but its returning old images, you can test the facebook, whatsapp and other apps, they generate different meta.

can you please let me know, how we can generate the latest one.

**Comment by inPhilly** [comment]
@Razanajam do you have any example links to demonstrate this?

**Comment by LeonardoCardoso** [comment]
Hi, the SLP shows what it gets. The implementation is different from those apps afore mentioned by you, so there's no way for me to know how they do that.
