### ISSUE TITLE
Error while adding via SPM

### ISSUE THREAD

**Issue by boywithaxe** [LeonardoCardoso/SwiftLinkPreview#117]
Tried adding SLP to a new project and I am getting an error about incompatible tools version.

> because SwiftLinkPreview >=0.1.0 contains incompatible tools version and root depends on SwiftLinkPreview 3.1.0..<4.0.0, version solving failed.

Are you planning an update? or is there a way to resolve this myself?

<img width="736" alt="image" src="https://user-images.githubusercontent.com/19761391/80303205-a45b7700-87a6-11ea-87a1-07f506887c1f.png">

**Comment by LeonardoCardoso** [comment]
New version with the fix coming right up.
