### ISSUE TITLE
for youtube share url not getting details like title, image etc

### ISSUE THREAD

**Issue by midhunnarayan22** [LeonardoCardoso/SwiftLinkPreview#126]
While sharing youtube URL from the app it is not getting a proper response 
https://youtu.be/MZWina8plDk

**Comment by MuhtasimTanmoy** [comment]
Also facing the same problem. Any solution?

**Comment by jscalo** [comment]
I'm trying to diagnose but if you look at the `htmlCode` sent to `performPageCrawling()`, the title is:

```
<title>YouTube</title>
```

So now all titles show up as "YouTube" instead of the original. I think it might have something to do with following the redirects.

**Comment by daveymcgav** [comment]
Yup, seeing this also!

**Comment by LeonardoCardoso** [comment]
Seems to be fixed with the new version.

![Simulator Screen Shot - iPhone 11 Pro - 2021-02-01 at 12 29 57](https://user-images.githubusercontent.com/1775157/106453196-38bade80-6489-11eb-9538-5879528e1926.png)
