### ISSUE TITLE
For YouTube Links, it is not fetching Video Thumbnail

### ISSUE THREAD

**Issue by dhanrajdc7** [LeonardoCardoso/SwiftLinkPreview#128]
Video Thumbnails is not being fetched.......

**Comment by VadimIdeasoft** [comment]
Experiencing with behavior for a +- week now as well.

**Comment by LeonardoCardoso** [comment]
I will have a look at it when I have time. The code is there, so feel free to explore it, find the issue and open a PR. Contribution is always welcome.

**Comment by dhanrajdc7** [comment]
I have done some debugging with SwiftLinkPreview & YouTube videos. 

**In RESPONSE, there are no images URL fetched in .image and .images.**

**Comment by LeonardoCardoso** [comment]
@dhanrajdc7 I might have a clue how to solve this.

Maybe YouTube has changed the metatag on their website or changed how they label images. You could try fixing it by identifying the change in the html source code of a video page.

_I am currently on vacations and have no computer around._

**Comment by dhanrajdc7** [comment]
Ok, I will give it a try

**Comment by LeonardoCardoso** [comment]
Seems to be fixed with the new version.
![Simulator Screen Shot - iPhone 11 Pro - 2021-02-01 at 12 29 57](https://user-images.githubusercontent.com/1775157/106453580-d1515e80-6489-11eb-85c9-777a6410fb93.png)
