### ISSUE TITLE
Could not find module 'SwiftLinkPreview' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator`

### ISSUE THREAD

**Issue by dastan1302** [LeonardoCardoso/SwiftLinkPreview#137]
Getting this error when running on Intel and M1 both macs with xcode 12.4, on latest OS BigSur

**Comment by LeonardoCardoso** [comment]
I'm closing this issue because I couldn't reproduce. Are you still having this problem?

**Comment by eliburke** [comment]
I got this error too, with XCode 13.
Runs on a device but I can't run an x86_64 simulator build (and I don't have an M1 Mac handy)

I've cleaned out my DerivedData and artifacts, and built using Carthage: 
`carthage update --platform iOS --no-use-binaries --cache-builds --use-xcframeworks`

Problem occurs when I run: 
Could not find module 'SwiftLinkPreview' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: ~/Library/Developer/Xcode/DerivedData/APP_BUILD_DIRECTORY/Build/Products/Debug-iphonesimulator/SwiftLinkPreview.framework/Modules/SwiftLinkPreview.swiftmodule

I was able to resolve the problem by removing the VALID_ARCHS lines. I think this is an older setting that was needed back in the day, but XCode 12/13 xcframeworks do not.

**Comment by Samigos** [comment]
I just got my first M1 mac and I get the exact same error! What is the fix here?

**Comment by eliburke** [comment]
It's right there in my [comment](https://github.com/LeonardoCardoso/SwiftLinkPreview/issues/137#issuecomment-937754535) along with a merge request. You can pin to my branch or fork and fix it for yourself.

**Comment by Samigos** [comment]
I tried pinning the pod to your branch (valid_archs), but cocoapods failed to find it! Indeed, there’s no branch with that name!

**Comment by eliburke** [comment]
Ah sorry... I'm used to Carthage which lets you easily point to different repos. I can't help you any further than google but maybe check out "cocoapods private repo" 

https://guides.cocoapods.org/making/private-cocoapods.html
