### ISSUE TITLE
Image tag not shown for Disney Plus links

### ISSUE THREAD

**Issue by haansplosion** [LeonardoCardoso/SwiftLinkPreview#142]
https://www.disneyplus.com/en-gb/series/the-bad-batch/4gMliqFxxqXC returns an SVG link, not correctly the og:image tag

**Comment by LeonardoCardoso** [comment]
Thanks for spotting this. I don't have the capacity to work on this right now. Feel free to contribute and open a PR.

**Comment by LeonardoCardoso** [comment]
Have you tested with the latest version? It seems to work for me.
![Simulator Screen Shot - iPhone 13 Pro - 2021-09-23 at 19 05 15](https://user-images.githubusercontent.com/1775157/134552186-656caad2-ed76-42e5-bf6a-c93e6d10cf94.png)
