### ISSUE TITLE
Regex mismatches (or allowing for more types of urls)

### ISSUE THREAD

**Issue by gadu** [LeonardoCardoso/SwiftLinkPreview#17]
Is this library only supposed support certain type of url formats?

When I tested it with www.google.com (or any other url without the http://) I got "No URL has been found"

Similarly, when I tried to use http://www.google.com I got "An error occurred when parsing the HTML"

It worked fine with the examples you used but I think requiring the http:// is a bit strict in that if a we are analyzing user typed messages, it might be quite common to see something like youtube.com which IS picked up by NSDataDetector as a link, but won't be valid as a link according to the regex you are using.

**Comment by LeonardoCardoso** [comment]
The intention of the project is to detect explicit URL. The Regex also detect `https` which are two of the, let's say, protocols that everyone uses for websites. I see your point though. I'm gonna improve URL detection and create tests for URL parsing. Wait a few days.

**Comment by LeonardoCardoso** [comment]
Apparently this Regex is what you're looking for. https://regex101.com/r/lY8vA0/1

**Comment by LeonardoCardoso** [comment]
@gadu Thanks again. Regex parsing was improved and I've added tests for all platforms.
Regards.

Closed by 0c5cbda.
