### ISSUE TITLE
Caching Results (Feature)

### ISSUE THREAD

**Issue by gadu** [LeonardoCardoso/SwiftLinkPreview#21]
Said it before, but again, great project.

Wanted to suggest a caching feature for web results. It seems like using this in some sort of feed or table view might be a common use case, so currently whenever that happens and cells are reused there are more network calls and work done in parsing the same exact content over and over.

It would be really cool and useful if it could cache results (maybe allow for customization on how many days) so that the same network requests wouldn't have to be made over and over again every time a view loads or a cell is reused.

**Comment by LeonardoCardoso** [comment]
Supported added in version [2.0.0](https://github.com/LeonardoCardoso/SwiftLinkPreview/releases/tag/2.0.0). Thanks to [@ypopovych](https://github.com/ypopovych).
