### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Droppix** [LeonardoCardoso/SwiftLinkPreview#24]
Hi,

Little suggestion : Integration of "favicon.ico"

Regards

**Comment by LeonardoCardoso** [comment]
Closed by #60.

**Comment by LeonardoCardoso** [comment]
![simulator screen shot 24 jul 2017 at 11 49 08](https://user-images.githubusercontent.com/1775157/28518126-235c06aa-7067-11e7-8709-e3915a9e33e5.png)
![simulator screen shot 24 jul 2017 at 11 48 52](https://user-images.githubusercontent.com/1775157/28518124-235a57f6-7067-11e7-93e9-f0d682a942f5.png)
![simulator screen shot 24 jul 2017 at 11 48 34](https://user-images.githubusercontent.com/1775157/28518125-235ae446-7067-11e7-8602-ff17232fc876.png)
![simulator screen shot 24 jul 2017 at 11 48 29](https://user-images.githubusercontent.com/1775157/28518127-23700ad8-7067-11e7-9bea-fae94d2161fe.png)
