### ISSUE TITLE
Cocoapods still not working

### ISSUE THREAD

**Issue by kuyazee** [LeonardoCardoso/SwiftLinkPreview#26]
it's me again haha.

Resolving dependencies of `Podfile`
[!] Unable to find a specification for `SwiftLinkPreview`

**Comment by LeonardoCardoso** [comment]
Are you using your connection behind some proxy or making some typo? CocoaPods is case sensitive. 

If you are using as a dependency for your own pod, notice that you have to specify the tag.
Instead of:

```
s.source = { :git => "git@github.com:myrepo/Podspecs.git", :branch => "xyz" }
```

Write this:

```
s.source  = { :git => "https://github.com/myrepo/Podspecs.git", :branch => "xyz", :tag => s.version.to_s }
```

It's alive and working.

https://cocoapods.org/pods/SwiftLinkPreview

**Comment by LeonardoCardoso** [comment]
Another solution is to deintegrate the Pods.

```
$ sudo gem install cocoapods-deintegrate
```

```
$ pod deintegrate
```

```
$ pod install
```

**Comment by kuyazee** [comment]
I have no idea why it doesn't work for me.. I'm using other libraries in my cocoapods as well. 

anyway I just this library in manually haha. thanks anyway

**Comment by kuyazee** [comment]
I figured out why it didn't work. my pod repo was outdated. sorry to have bugged you. btw thanks for the library again it's a great help

**Comment by LeonardoCardoso** [comment]
@kuyazee That's why I told you to update and deintegrate your pod. Regards.
