### ISSUE TITLE
Use this in Objective c Project

### ISSUE THREAD

**Issue by RakeshImpinge** [LeonardoCardoso/SwiftLinkPreview#29]
How to use this library in Objective c project?

**Comment by LeonardoCardoso** [comment]
Hi, @RakeshImpinge.

You can follow the official documentation https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by RobertNNms** [comment]
Hi,

Implementation with Objective-C, don't work! (XCode 8)
For this to work, SwiftLinkPreview must inherit the NSObject class.

> open class SwiftLinkPreview : NSObject {...}

**Comment by LeonardoCardoso** [comment]
Hey, @RobertNNms and @RakeshImpinge.

I've created a new version with this compatibility. https://github.com/LeonardoCardoso/SwiftLinkPreview/releases/tag/1.0.1
