### ISSUE TITLE
some bit.ly Links causes the app to lag (until the url gets loaded)

### ISSUE THREAD

**Issue by kuyazee** [LeonardoCardoso/SwiftLinkPreview#32]
I think this is some kind of small problem for the dispatch or thread,  but I'm still not really adept at that part of coding so I don't know. 

http://bit.ly/2dIBlR6 here's the link btw

But once again. This project is so kickass awesome. Thanks :)

**Comment by LeonardoCardoso** [comment]
Do you have more examples?

**Comment by kuyazee** [comment]
I'll try looking for more links like these. (I think it's because the link redirects to a PDF)

http://bit.ly/2dKjZUz

**Comment by LeonardoCardoso** [comment]
To capture the real URL request is synchronous because we need to follow the redirections of a short url, but the rest is not.

**Comment by kuyazee** [comment]
really? cause even when I'm just trying to load links like www.github.com (I type in a textfield a link and I detect if the link is of the legit format then every tap I load it by adding a target to my textfield .EditingChanged)

so everytime I tap it tries to load (so it lags/delays a little bit) so I changed loading of url's to textField didEndEditing

**Comment by LeonardoCardoso** [comment]
Can you try with the new version?

**Comment by LeonardoCardoso** [comment]
Closed due inactivity.
