### ISSUE TITLE
The file “Dev” couldn’t be opened because you don’t have permission to view it.

### ISSUE THREAD

**Issue by gabrielapittari** [LeonardoCardoso/SwiftLinkPreview#33]
XCode version 7.2.1 and Mac 10.11.6
Development target: iOS 8.4
Swift 2.1

Error:
It was building but when installing the app on the device I was getting:

> The file “Dev” couldn’t be opened because you don’t have permission to view it.

I solved the issue by doing the following:

- Downloaded: https://github.com/LeonardoCardoso/SwiftLinkPreview/releases/tag/0.1.6

- Added the unzipped folder to my Libraries in my project.

- From the SwiftLinkPreview folder removed the all the plists except for the Info.plist, Example folder, package.swift

- Removed derived data, clean the project

- Add the binary to my project: General->Embedded Binaries

**Comment by LeonardoCardoso** [comment]
Thanks, @gabrielapittari!

**Comment by LeonardoCardoso** [comment]
The problem was detected by issue #34 and fixed by e7ec20b3ec6fb68cfa2118693621e3b3564b6db8.
