### ISSUE TITLE
iOS 8 compatibility

### ISSUE THREAD

**Issue by kuyazee** [LeonardoCardoso/SwiftLinkPreview#38]
By any chance could you lower the compatibility of the Swift 3 version to iOS 8?

**Comment by LeonardoCardoso** [comment]
My main focus for this project is iOS 9+, although it supported iOS 8 before Swift 3. Can you fork this project, low the minimum version, do some tests and CI tests (take a look at .travis.yml and tests.sh) for iOS 8, then create a PR?

**Comment by kuyazee** [comment]
Okay will do I'll update you

**Comment by LeonardoCardoso** [comment]
Done.
