### ISSUE TITLE
CRASH when no URLs present.

### ISSUE THREAD

**Issue by andrewbellay** [LeonardoCardoso/SwiftLinkPreview#39]
First off, thanks for a nice open-source repo.

*The Issue*
Line 122 in SwiftLinkPreview.swift results in a crash if the text in question contains no URLs. In line, 121 the 'pieces' array ends up being empty if there's no URL and then the first element is grabbed in the following line, resulting in a 'fatal error: Index out of range' exception and crash.

Unfortunately, I'm short on time or I would make a PR with a robust solution, however, I might recommend checking the count of the array or using the 'first' property, which fails more gracefully than the subscript 'pieces[0]'

Thanks again

**Comment by LeonardoCardoso** [comment]
Hi. Thanks. I'll do it when I have time. Feel free to send PR though.
