### ISSUE TITLE
2.0.2 adds ambiguous method error in Swift builds

### ISSUE THREAD

**Issue by giffnyc** [LeonardoCardoso/SwiftLinkPreview#41]
My bad - the preview method wrapper I added for Objective-C compatibility conflicts with the Swift version, in Swift builds (not in Objective-C builds), causing the compiler to generate an error about ambiguous methods.

Solution is to provide an alternate name for the method.  Will post pull request.

**Comment by LeonardoCardoso** [comment]
Thanks, @giffnyc.
