### ISSUE TITLE
Ambiguous error

### ISSUE THREAD

**Issue by chashmeetsingh** [LeonardoCardoso/SwiftLinkPreview#43]
Tried running the example project and the following comes up. @LeonardoCardoso 
<img width="217" alt="screen shot 2017-03-21 at 7 21 42 pm" src="https://cloud.githubusercontent.com/assets/8962264/24150423/b68aed3c-0e6b-11e7-9c67-bc8cff5c751c.png">

**Comment by LeonardoCardoso** [comment]
Hi @chashmeetsingh. Have you installed the dependencies described [here](https://github.com/LeonardoCardoso/SwiftLinkPreview/tree/master/Example)?

**Comment by chashmeetsingh** [comment]
Yes, i did

**Comment by LeonardoCardoso** [comment]
This is weird. I just downloaded here and it worked perfectly.

**Comment by chashmeetsingh** [comment]
<img width="261" alt="screen shot 2017-03-21 at 10 20 29 pm" src="https://cloud.githubusercontent.com/assets/8962264/24159243/a6737932-0e84-11e7-8f15-59878eafb7be.png">
<img width="1512" alt="screen shot 2017-03-21 at 10 20 39 pm" src="https://cloud.githubusercontent.com/assets/8962264/24159245/a6a65ca8-0e84-11e7-8873-bf648e45c384.png">

**Comment by LeonardoCardoso** [comment]
Try to clean derived data.

**Comment by chashmeetsingh** [comment]
Nope, doesn't still seem to work :(

**Comment by LeonardoCardoso** [comment]
Sorry, but I don't really know what's causing it. Here it works!![screen shot 2017-03-21 at 18 06 21](https://cloud.githubusercontent.com/assets/1775157/24160049/2c7211a2-0e61-11e7-8b6c-66a60680cd4b.png)

**Comment by chashmeetsingh** [comment]
No problem, will figure some workaround 👍
