### ISSUE TITLE
Hangs when crawling for description

### ISSUE THREAD

**Issue by taykay08** [LeonardoCardoso/SwiftLinkPreview#44]
The URL I'm crawling is: https://www.flickr.com/explore/

I stepped through the source and see that it's hanging in crawlDescription() at the crawlCode() call.

I see this in the debugger console: SendDelegateMessage(NSInvocation *): delegate (<CFNotificationCenter 0x6080000aed60 [0x108679df0]>) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode

**Comment by LeonardoCardoso** [comment]
Hey @taykay08. Thanks. I'll have a look.

**Comment by LeonardoCardoso** [comment]
This is weird, here it works.

**Comment by taykay08** [comment]
Ok, thanks for checking. Maybe it's on my end - I'll try to isolate it in a new project.

**Comment by LeonardoCardoso** [comment]
Ok. Please let me know.

**Comment by taykay08** [comment]
Yikes, thought I had grabbed the latest code, I guess I didn't. Anyway, it seems to be working the same as yours now. Takes about a minute, but happy to see it hit the completion method now. Sorry about that, and thanks for the quick response!
