### ISSUE TITLE
Make URL detection work for text containing new-lines

### ISSUE THREAD

**Issue by marchy** [LeonardoCardoso/SwiftLinkPreview#47]
Very simple fix here, too short for doing pull-request:

Simply change line 207 in SwiftLinkPreview::extractURL(text)
from:
```let pieces: [String] = text.components(separatedBy: " ").filter { $0.trim.isValidURL() }```
to:
```let pieces: [String] = text.components(separatedBy: .whitespacesAndNewlines).filter { $0.trim.isValidURL() }```

PS: Do you mind also making the extractURL(...) method public? It's really useful UX-wise to determine whether a URL WOULD be detected and do some logic against the previously-detected one and thus ONLY invoke a new preview(..) if the URL is different. This happens when typing in a text-field for example and you don't want to fire a new request off upon every keystroke. Instead only want when the detected URL has actually changed.

Cheers!

**Comment by LeonardoCardoso** [comment]
Hey @marchy. Thanks.
Please do the PR! :D
