### ISSUE TITLE
There is no guide to build Example

### ISSUE THREAD

**Issue by AmmarMujeeb** [LeonardoCardoso/SwiftLinkPreview#50]
Although its not an issue in the project but just if someone wants to run the Example then they need to initialize pod and following pods are required.

  # Pods for SwiftLinkPreviewExample
    pod 'SwiftLinkPreview', '~> 2.0.4'
    pod 'SwiftyDrop', '~>3.0'
    pod 'ImageSlideshow'
    pod 'Alamofire'
    pod 'AlamofireImage'
end

**Comment by LeonardoCardoso** [comment]
Hi, have you read [/Example/Readme.md](https://github.com/LeonardoCardoso/SwiftLinkPreview/tree/master/Example/Readme.md)?

**Comment by AmmarMujeeb** [comment]
No i missed, My bad. But i go through the first README page and in the index also there was nothing regarding this Example instead there were Visual Examples only. Just a suggestion, if you mention it in the index you created that would be much helpful.

**Comment by LeonardoCardoso** [comment]
Thanks.

If you simply go to [Example](https://github.com/LeonardoCardoso/SwiftLinkPreview/tree/master/Example), the README is displayed. Maybe I'll mention it in the main README next time I change the code.
