### ISSUE TITLE
not working for linkedin

### ISSUE THREAD

**Issue by AashishNagar** [LeonardoCardoso/SwiftLinkPreview#51]
library not working with url "https://www.linkedin.com". Image not coming.

**Comment by LeonardoCardoso** [comment]
This is very subjective. Also LinkedIn might have changed the way they allow robot scrapping. I'm gonna take a look that when I have time.

**Comment by LeonardoCardoso** [comment]
I've changed a few things and managed to get the preview of LinkedIn. But in fact, those images are loaded via javascript. There's nothing much I can do about it. 

![simulator screen shot - iphone 8 plus - 2018-01-06 at 06 36 26](https://user-images.githubusercontent.com/1775157/34636943-0a48c9d8-f2ac-11e7-9aad-ae9b41c93b52.png)
