### ISSUE TITLE
Make extractURL public

### ISSUE THREAD

**Issue by marchy** [LeonardoCardoso/SwiftLinkPreview#52]
Hi there could you please make the extractURL(...) method public?

This is really useful UX-wise to determine whether a URL _WOULD_ be detected and do some logic against the previously-detected one and thus ONLY invoke a new preview(..) if the URL is different. 

This happens when the user types in a text-field and you don't want to fire a new request upon every keystroke. Instead only want to do so when the detected URL has actually changed from the previous one. For example if they type a link in a comment text box and continue to type their message afterwards, the rest of the keystrokes will resolve to the same URL and thus you can skip the URL fetching.

NOTE: The only change required for this is to change the 'internal' keyword to 'public' in the SwiftLinkPreview extension's extractURL(text:) method.

Thx!

**Comment by LeonardoCardoso** [comment]
Fair enough. This is a good point. Done.

**Comment by LeonardoCardoso** [comment]
Fair enough. This is a good point. I've add it on version [2.0.5](https://github.com/LeonardoCardoso/SwiftLinkPreview/releases/tag/2.0.5).

**Comment by marchy** [comment]
Awesome, thanks Leonardo!
Now THAT'S turnaround  =)
