### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value (lldb) 

### ISSUE THREAD

**Issue by haansplosion** [LeonardoCardoso/SwiftLinkPreview#53]
Hi there, after updating to the latest version of Hero I am getting the error

```
fatal error: unexpectedly found nil while unwrapping an Optional value (lldb) 
```

On line 24 of **Lexer.swift:**
```
("\\-?[0-9.]+", { .number(Float($0)!, $1) }),
```
<img width="1443" alt="screen shot 2017-06-10 at 6 51 25 pm" src="https://user-images.githubusercontent.com/6058393/27001455-d260c608-4e0d-11e7-8d3b-ba0423b885ed.png">

**_Xcode - Version 8.3.3 (8E3004b)
Swift 3_**

**Comment by LeonardoCardoso** [comment]
Seems it's not related to my library.

**Comment by haansplosion** [comment]
Sorry, I thought Lexer was a dependancy of your library working?

https://github.com/lkzhao/Hero/blob/master/Sources/Parser/Lexer.swift

**Comment by haansplosion** [comment]
Deepest apologies, wrong repo!
