### ISSUE TITLE
Twitter return errors

### ISSUE THREAD

**Issue by chrisvanbuskirk** [LeonardoCardoso/SwiftLinkPreview#57]
First nice lib, but a few problems.

Twitter

Error Domain=NSPOSIXErrorDomain Code=100 "Protocol error" UserInfo={NSErrorPeerAddressKey=<CFData 0x618000281270 [0x101e3bbc0]>{length = 16, capacity = 16, bytes = 0x100201bb68f42ac10000000000000000}, _kCFStreamErrorCodeKey=100, _kCFStreamErrorDomainKey=1}

Linkedin fails as well.  I don't know why yet.

**Comment by LeonardoCardoso** [comment]
Hi, @chrisvanbuskirk. Thank you. As mentioned in #51 They might have changed the way they allow robot scrapping. I'm gonna take a look that when I have enough time.

**Comment by LeonardoCardoso** [comment]
I've changed a few things and managed to get the preview of Twitter. Please use the newest release. 

![simulator screen shot - iphone 8 plus - 2018-01-06 at 06 39 52](https://user-images.githubusercontent.com/1775157/34636968-750c01a4-f2ac-11e7-9825-7e70458f048d.png)
![simulator screen shot - iphone 8 plus - 2018-01-06 at 06 39 40](https://user-images.githubusercontent.com/1775157/34636969-7524153c-f2ac-11e7-9898-9fd0fb4fb5c1.png)
