### ISSUE TITLE
SwitLinkPreview Not Getting Detail URLS..

### ISSUE THREAD

**Issue by balkrishanyadav** [LeonardoCardoso/SwiftLinkPreview#58]
Hi, Swift Link preview is not getting image, description, url for no of below URL's ..
1. https://youtu.be/wH6tWW_gWsA 
2. http://www.miniclub.rocks/
3. https://www.linkedin.com/ 
etc.
Please help me for resolve issues for  urls...

Thanks,

**Comment by LeonardoCardoso** [comment]
Duplicate #51

**Comment by LeonardoCardoso** [comment]
I've changed a few things and managed to get the preview of the cited websites. Please use the newest release. 

![simulator screen shot - iphone 8 plus - 2018-01-06 at 04 57 31](https://user-images.githubusercontent.com/1775157/34636940-09f070a8-f2ac-11e7-887b-d4a0bad0f5ee.png)
![simulator screen shot - iphone 8 plus - 2018-01-06 at 04 57 56](https://user-images.githubusercontent.com/1775157/34636941-0a0d96f6-f2ac-11e7-9ba7-99376718e309.png)
![simulator screen shot - iphone 8 plus - 2018-01-06 at 05 11 01](https://user-images.githubusercontent.com/1775157/34636942-0a2ba95c-f2ac-11e7-9312-2c7a68c3e7d8.png)
![simulator screen shot - iphone 8 plus - 2018-01-06 at 06 36 26](https://user-images.githubusercontent.com/1775157/34636943-0a48c9d8-f2ac-11e7-9aad-ae9b41c93b52.png)

**Comment by balkrishanyadav** [comment]
Thanx
