### ISSUE TITLE
Wrong description coming

### ISSUE THREAD

**Issue by SourabhYapApp** [LeonardoCardoso/SwiftLinkPreview#59]
Used link : http://www.ndtv.com/video/exclusive/news/i-have-evidence-of-special-favours-to-sasikala-whistleblower-cop-roopa-463151

Json:
[SwiftLinkPreview.SwiftLinkResponseKey.canonicalUrl: "m.ndtv.com", SwiftLinkPreview.SwiftLinkResponseKey.description: "Home",  ...

Actual Description is different. 
Also facing similar issue in some other links too.

**Comment by LeonardoCardoso** [comment]
Apparently description in 'http://www.ndtv.com' is different the one in from 'm.ndtv.com'.

**Comment by LeonardoCardoso** [comment]
I've changed few things and managed to get the preview of the cited website. Please use the newest release. 

![simulator screen shot - iphone 8 plus - 2018-01-06 at 06 47 32](https://user-images.githubusercontent.com/1775157/34637021-7f8b7118-f2ad-11e7-8789-40acc095f71f.png)
