### ISSUE TITLE
Unable to parse

### ISSUE THREAD

**Issue by SourabhYapApp** [LeonardoCardoso/SwiftLinkPreview#61]
"https://goo.gl/maps/8cu9dtwedbn" is a shared link from google maps. In most of the cases we getting "This URL cannot be opened" and localised description as "The operation couldn’t be completed. (SwiftLinkPreview.PreviewError error 2.)". And if it successful then also we are unable to get image.

**Comment by SourabhYapApp** [comment]
For apple map link as:
https://maps.apple.com/?ll=30.676222,76.740431&q=Sourabh%20Sharotria%E2%80%99s%20Location&t=m

Iam getting response

SwiftLinkPreview.SwiftLinkResponseKey.canonicalUrl: "**www.google.com**", SwiftLinkPreview.SwiftLinkResponseKey.title: "**Google Maps**"

**Comment by LeonardoCardoso** [comment]
Links like that have many redirections and sometimes they block scraping.
