### ISSUE TITLE
Cancel not available swift 3.1

### ISSUE THREAD

**Issue by Urvish-modi** [LeonardoCardoso/SwiftLinkPreview#62]
Try to accessing linkpreviewobject.cancel not available

**Comment by LeonardoCardoso** [comment]
Hi, you do not call `linkpreviewobject.cancel`. It was misdocumented. 
You can call cancel like this instead:

```
let cancelabelPreview = linkpreviewobject.preview(...)
cancelabelPreview.cancel()
```
