### ISSUE TITLE
Is there a way to tell if the site contains porn/gambling material?

### ISSUE THREAD

**Issue by inPhilly** [LeonardoCardoso/SwiftLinkPreview#64]
I don't want to show a preview for any site that is pornographic or gambling related (or anything else that would be inappropriate). Is there a way to check for those categories using this repository?

**Comment by LeonardoCardoso** [comment]
Not yet.

**Comment by inPhilly** [comment]
Okay. I will let you know if I find anything about that. By the way, should this be run on a background thread?

**Comment by LeonardoCardoso** [comment]
What should be?! SLP or filtering?
