### ISSUE TITLE
Not Safe in Application Extensions?

### ISSUE THREAD

**Issue by inPhilly** [LeonardoCardoso/SwiftLinkPreview#65]
I am trying to build my App Extension with SwiftLinkPreview and I am  getting this error:
warning: linking against a dylib which is not safe for use in application extensions: .../Carthage/Build/iOS/SwiftLinkPreview.framework/SwiftLinkPreview

Is it true that this library is not save in app extensions? if so, is there anything I can do to make it safe? Thanks.

**Comment by LeonardoCardoso** [comment]
@inPhilly 

> In the target for your extension there is a build setting in the "build options" section - "Require Only App-Extension-Safe API". If it isn't enabled already, try enabling it...

Check out this thread https://stackoverflow.com/q/28652102/1255990.

**Comment by LeonardoCardoso** [comment]
Closed due lack of response.
