### ISSUE TITLE
finished with error - code: -1001

### ISSUE THREAD

**Issue by BorjaCloobing** [LeonardoCardoso/SwiftLinkPreview#70]
Some urls are giving me be back this error "finished with error - code: -1001"
I have searched that incoming url, is well built. Any idea?

**Comment by LeonardoCardoso** [comment]
Which ones?

**Comment by LeonardoCardoso** [comment]
Closed by the lack of response

**Comment by kirualex** [comment]
I get `finished with error - code: -1002` for this URL : https://www.theguardian.com/world/2018/jan/10/two-suns-no-its-a-supernova-drawn-6000-years-ago-say-indian-scientists

**Comment by LeonardoCardoso** [comment]
@kirualex Which version?

**Comment by kirualex** [comment]
2.2.0 on iOS11

**Comment by LeonardoCardoso** [comment]
Please test the version on maste.

**Comment by LeonardoCardoso** [comment]
Related to #86

**Comment by LeonardoCardoso** [comment]
I don't see any errors performing it here.

<img width="1474" alt="screen shot 2018-06-07 at 14 36 05" src="https://user-images.githubusercontent.com/1775157/41099896-29219b1a-6a60-11e8-8638-b8d5d7c77d5a.png">

The only problem I'm having is that the pictures are unauthorized outside their website.

<img width="1267" alt="screen shot 2018-06-07 at 14 35 37" src="https://user-images.githubusercontent.com/1775157/41099942-4556f97e-6a60-11e8-99cb-85e841e84b70.png">
