### ISSUE TITLE
No response and error

### ISSUE THREAD

**Issue by oskarmt** [LeonardoCardoso/SwiftLinkPreview#71]
Hello! Can you help me?
I'm trying to check if this URL(http://eventakzent.de/wp-content/uploads/Vid-Silvester/silvester17-black&gold-promo-FINAL.mp4) contains any titles, images or etc.. and  have no response on this request. If there are a lot of such links on the screen, cpu = 100%. How do you handle such links with files?

**Comment by LeonardoCardoso** [comment]
It's not supported, unless it's an image. Otherwise it will return nothing.
