### ISSUE TITLE
off by one error

### ISSUE THREAD

**Issue by tamoyal** [LeonardoCardoso/SwiftLinkPreview#72]
I think:

```
if text.count > range.location + range.length {
   return (text as NSString).substring(with: range)
}
```

should be `>=`

just eyeballed it

**Comment by LeonardoCardoso** [comment]
Hey, did it crash? What website were you trying to preview?

**Comment by tamoyal** [comment]
No I think the end result is extracting a link from text which is JUST a link won't work because it's off by 1. If you don't see what I see I can test again today

**Comment by LeonardoCardoso** [comment]
Please try it and let me know.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tamoyal** [comment]
Maybe I'm not totally understanding your code. I see you don't use `Regex.rawUrlPattern` to extract urls (you use `NSDataDetector`), just to test if a string is a url. Anyway, this is what fails (and you tell me if you think it should pass):
```
    func testPregMatchFirst() {
        XCTAssertEqual(Regex.pregMatchFirst("http://www.google.com", regex: Regex.rawUrlPattern)!, "http://www.google.com")
        XCTAssertEqual(Regex.pregMatchFirst(" http://www.google.com", regex: Regex.rawUrlPattern)!, "http://www.google.com")
        XCTAssertEqual(Regex.pregMatchFirst("http://www.google.com ", regex: Regex.rawUrlPattern)!, "http://www.google.com")
        XCTAssertEqual(Regex.pregMatchFirst(" http://www.google.com ", regex: Regex.rawUrlPattern)!, "http://www.google.com")
    }
```

**Comment by LeonardoCardoso** [comment]
This code you are seeing is outdated. And regarding your first question, no changes were detected after applying `>=`.
