### ISSUE TITLE
Invalid url returned for image url

### ISSUE THREAD

**Issue by tamoyal** [LeonardoCardoso/SwiftLinkPreview#74]
For this site: http://www.dailymail.co.uk/news/article-4920958/Company-creates-45-000-flat-pack-surf-shacks.html?ITO=1490&ns_mchannel=rss&ns_campaign=1490

We get for the image url this:
```
"http://www.facebook.com/tr?id=1401367413466420&amp;ev=NoScript\" /></noscript> <div id=\"lightbox-target\" class=\"lightbox-gallery hidden\"></div> <div class=\"page_banner_overrides page page-banner articlePage\" id=\"top\"> <div class=\"banner-adverts\"> </div> <div id=\"page-container\"><div class=\"clear\">&nbsp;</div><div class=\"page-header bdrgr2\"><div class=\"news\"><div class=\"masthead \"><a href=\"/\"><img alt=\"MailOnline - news, sport, celebrity, science and health stories\" height=\"66\" id=\"logo\" src=\"http://i.dailymail.co.uk/i/sitelogos/logo_mol.gif"
```

Which crashes `Url(string: imageURL)!` so the url extractor you are using doesn't play nicely with the parser

**Comment by LeonardoCardoso** [comment]
- I would consider never force wrap my code
- I didn't have any issues parsing the url you mentioned. I've done some improvements though. Try it with the version on master.
