### ISSUE TITLE
Fail to redirect in some cases. 

### ISSUE THREAD

**Issue by mihirpmehta** [LeonardoCardoso/SwiftLinkPreview#76]
If you compare the result with facebook or even some other Library like Kanna .... in some sites the image is different as it grabs the image before redirection 

for Example http://www.timesofindia.indiatimes.com never displays TOI image in SwiftLinkPreview ... where as other library as well as Kanna displays TOI image as the main background (Red color background with white colored TOI written )

**Comment by LeonardoCardoso** [comment]
It's unfair to compare my lib to Facebook's. I've never heard about Kanna. I don't know how they parse it. And TimesOfIndia shows a annoying ad before allowing you to go to the proper site.
