### ISSUE TITLE
Swift 4 Support Planned?

### ISSUE THREAD

**Issue by brianturney** [LeonardoCardoso/SwiftLinkPreview#77]
Will this eventually support Swift 4?  Tried this in Xcode 9 Swift 4 and just errors everywhere.  Doesn't work.

**Comment by eliburke** [comment]
Works fine for me via Carthage (and presumably CocoaPods and SPM). Are you manually including the  sources in your project?

**Comment by brianturney** [comment]
I opened the project direct from the Github download and did the pod install.  Had tons of errors.  Not sure whats up. Doesnt work.

**Comment by brianturney** [comment]
I got it working but it ultimately doesnt do what I thought it did.  links open in safari instead of a webview inside the app.  Videos won't play, you just get an image of the video.  This is nothing like FB's preview.   It's nice for static images and content you don't have to interact with.

**Comment by eliburke** [comment]
It’s called SwiftLinkPreview, not SwiftYourAppWrittenForYou 😜

I think the Readme is pretty clear on what this framework does. Scrape a URL and return the metadata/images. The sample app is just an example of how to use it. Personally, I GET the main image, render the title/description, and add a tap handler that opens in a web view. Works similar to iMessages (minus video, but that’s on me to implement)

If you need to download and play video, maybe look at AlamoFire and one of the many video player components on github?

**Comment by LeonardoCardoso** [comment]
https://github.com/LeonardoCardoso/SwiftLinkPreview/issues/66
