### ISSUE TITLE
Speed detect link

### ISSUE THREAD

**Issue by nguyentrai2011** [LeonardoCardoso/SwiftLinkPreview#78]
Thanks for your lib

But I recognize with the same link, iOS detect slower than Android
This link: http://www.dailymail.co.uk/health/article-5381859/Why-pet-good-health.html
Could you please help me

Thanks,

**Comment by LeonardoCardoso** [comment]
This can be related to lots of external factors, such as internet connection, parsing speed, etc.

**Comment by nguyentrai2011** [comment]
@LeonardoCardoso Thanks for you response 
I use the same Network connection, I don't think the original parsing speed is to much difference between iOS and Android.
Do you try by yourselves?
