### ISSUE TITLE
Can't get image, description or title from link

### ISSUE THREAD

**Issue by onurgenes** [LeonardoCardoso/SwiftLinkPreview#83]
Trying to get preview from "www.dji.com/matrice600-pro/info#specs" but it returns 404.

Any idea?

**Comment by LeonardoCardoso** [comment]
What's the urls you are getting as response?

**Comment by onurgenes** [comment]
"url": www.dji.com/matrice600-pro/info#specs
"finalUrl": https://www.dji.com/404?url=http%3A%2F%2Fwww.dji.com%2Fmatrice600-pro%2Finfo#specs
"canonicalUrl": http://www.dji.com/matrice600-pro/info#specs

These are returning urls.

**Comment by onurgenes** [comment]
Waiting eagerly for fix. Thanks.

**Comment by LeonardoCardoso** [comment]
New method added. Check it out on `master` (Soon in a new release).

<img width="1639" alt="screen shot 2018-06-07 at 15 41 47" src="https://user-images.githubusercontent.com/1775157/41103391-506c61d8-6a69-11e8-8a7d-733c4a0be057.png">

**Comment by onurgenes** [comment]
Will check it out soon.
