### ISSUE TITLE
Get the wrong twitter preview if there is no image

### ISSUE THREAD

**Issue by daicatrungisme1** [LeonardoCardoso/SwiftLinkPreview#84]
if twitter no  image title, description is wrong
this is url https://twitter.com/lecaoquochung/status/770500828658593792
![img_0919](https://user-images.githubusercontent.com/32670658/40414986-f5a3b93e-5ea3-11e8-8920-81973bbd62db.PNG)
![img_0920](https://user-images.githubusercontent.com/32670658/40414988-f5de9252-5ea3-11e8-94e9-5162928ecf2d.PNG)

**Comment by LeonardoCardoso** [comment]
Duplicate #83
