### ISSUE TITLE
Cannot invoke initializer for type 'Range<_>' with an argument list of type '(Range<String.Index>)' in func substring(start:end:)

### ISSUE THREAD

**Issue by boywithaxe** [LeonardoCardoso/SwiftLinkPreview#85]
```

func substring(_ start: Int, end: Int) -> String {
return String(self[Range(self.index(self.startIndex, offsetBy: start) ..< self.index(self.startIndex, offsetBy: end))])

    }
```
the above function contains a method resulting in the following error:

Cannot invoke initializer for type 'Range<_>' with an argument list of type '(Range<String.Index>)' in Xcode 10 beta 1.

I appreciate this is a very early report, but does seem to be a swift version issue.

**Comment by LeonardoCardoso** [comment]
Most probably it is. I'll have a look ASAP.

**Comment by LeonardoCardoso** [comment]
Changes in `master`.

**Comment by MichaelLuoSyd** [comment]
Hi, may I know how to solve this issue please? I am having the same problem. Thanks

**Comment by LeonardoCardoso** [comment]
@MichaelLuoSyd Changes are in `master`!

**Comment by jpmhglance** [comment]
Was this it?

```
-         return String(self[Range(self.index(self.startIndex, offsetBy: start) ..< self.index(self.startIndex, offsetBy: end))])
+         return self.substring(NSRange(location: start, length: end - start))
```

I fixed a similar error in my code this way instead:

```
-                        self.text = String(str[Range(startIndex ..< nextToEndIndex)])
+                        self.text = String(str[startIndex ..< nextToEndIndex])
```

**Comment by boywithaxe** [comment]
That's the line that fixes it. the issue recurred in the latest version, but making the following change fixes it in Swift 4 and up

`-         return String(self[Range(self.index(self.startIndex, offsetBy: start) ..< self.index(self.startIndex, offsetBy: end))])
+         return self.substring(NSRange(location: start, length: end - start))`
