### ISSUE TITLE
Not able to use SwiftLinkPreview on Wix hosted sites

### ISSUE THREAD

**Issue by halinebr** [LeonardoCardoso/SwiftLinkPreview#86]
Whenever I attempt to run SwiftLinkPreview on a website that is hosted by Wix.com I receive `Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service` in the console, the callback on the preview function never returns, and the CPU usage drives up like crazy.

Is there a way to add/change request headers for the request?

Some examples for you guys to try:
https://www.yourgesture.com/
https://www.monicapackpilates.com/
https://www.yourgesture.com/
http://www.adammccain.org/

**Comment by LeonardoCardoso** [comment]
I'll have a look ASAP.

**Comment by LeonardoCardoso** [comment]
Hi, The content of Wix pages is loaded by several `iframes` and they are loaded after the page is loaded. So it gets very hard to extract info.

<img width="939" alt="screen shot 2018-06-07 at 15 51 36" src="https://user-images.githubusercontent.com/1775157/41104230-2f134e82-6a6b-11e8-94fd-0054c84d892e.png">

I managed to extract information. It is limited information.

<img width="1315" alt="screen shot 2018-06-07 at 15 52 09" src="https://user-images.githubusercontent.com/1775157/41104257-385bf99e-6a6b-11e8-8c0e-7d519d26c36f.png">

<img width="1173" alt="screen shot 2018-06-07 at 16 26 21" src="https://user-images.githubusercontent.com/1775157/41106125-ab3b9df8-6a6f-11e8-9f0c-f90066b6f6d0.png">
<img width="1230" alt="screen shot 2018-06-07 at 16 26 56" src="https://user-images.githubusercontent.com/1775157/41106127-ab54bedc-6a6f-11e8-9b80-267851b02d1b.png">

**Comment by halinebr** [comment]
Thanks!

**Comment by LeonardoCardoso** [comment]
@halinebr I've just pushed a new version with the ability to get limited information from Wix websites. Version `2.3.0`.
