### ISSUE TITLE
Preview callback slow than before

### ISSUE THREAD

**Issue by iceboxi** [LeonardoCardoso/SwiftLinkPreview#88]
I compare version 2.3.0 with version 2.2.0
Most URL work fine, but like "tw.yahoo.com", 
version 2.3.0 callback about 7 sec.  
version 2.2.0 callback about 4 sec.

**Comment by LeonardoCardoso** [comment]
Nothing was touched in the code to reduce the performance. Can you tell me how you did your test? Same network? Same time with both versions running?

I've noticed that with GDPR, they have added new redirections to get to the final result.

```
canonicalUrl: tw.mobi.yahoo.com
title: Yahoo行動版
finalUrl: https://tw.mobi.yahoo.com/
image: http://l.yimg.com/os/mit/media/m/social/images/social_default_logo-1481777.png
description: 提供最方便的網站搜尋、即時新聞、生活資訊和Yahoo奇摩服務入口。
url: http://tw.yahoo.com
images: ["http://l.yimg.com/os/mit/media/m/social/images/social_default_logo-1481777.png"]
icon: https://s.yimg.com/ud/hp/ud/mit/td/hr/1126/appicon_72.png
```
