### ISSUE TITLE
Get Cache Response not working

### ISSUE THREAD

**Issue by shaharukhs** [LeonardoCardoso/SwiftLinkPreview#94]
Hi,

I am using `XCode 10.1`, `iOS 12.1` and `pod 'SwiftLinkPreview', '~> 2.3.1'`

When I try to fetch cache response it does not return anything.

I am attaching my demo sample please check.
[SwiftLinkPreviewDemo.zip](https://github.com/LeonardoCardoso/SwiftLinkPreview/files/2610485/SwiftLinkPreviewDemo.zip)

**Comment by LeonardoCardoso** [comment]
Hey @shaharukhs, I will have a look at it ASAP.

**Comment by LeonardoCardoso** [comment]
It's working in my repo's demo. Can you try it again using the most recent code?
