### ISSUE TITLE
Cannot assign to immutable expression of type 'URLSession.Type'

### ISSUE THREAD

**Issue by UtkuDalmaz** [LeonardoCardoso/SwiftLinkPreview#96]
<img width="860" alt="screen shot 2018-11-29 at 12 04 59" src="https://user-images.githubusercontent.com/2130592/49210795-102d8a80-f3cf-11e8-9ed8-d64489204afa.png">

**Comment by Faari7** [comment]
hi, i need to know how did you resolve this issue?

**Comment by nikitagudkovs** [comment]
I am facing the same issue.
