### ISSUE TITLE
Wrong Description

### ISSUE THREAD

**Issue by iceboxi** [LeonardoCardoso/SwiftLinkPreview#97]
I try this url (https://www.bnext.com.tw/article/51537/gamania-teamup)
And I get description with javascript code

![img_3875240738c4-1](https://user-images.githubusercontent.com/1142675/49567392-851d3900-f968-11e8-9fdd-bd24a56c0811.jpeg)

SwiftLinkPreview: 2.3.1
xCode 10.1 with last swift version

**Comment by LeonardoCardoso** [comment]
What do you consider the right description? Maybe you should think twice before writing an issue title.
